# Generated by Django 5.1.4 on 2024-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(related_name='games', to='task1.buyer'),
        ),
    ]
