# Generated by Django 5.1.4 on 2024-12-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
